version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    #logging:
    #    driver: none
  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    #volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock
    #logging:
    #    driver: none

  build:
    build:
      context: .
      target: build

    depends_on:
      - zookeeper
      - kafka

    command: ["true"]

    environment:
      KAFKA_URL: kafka:9092
      ZOOKEEPER_URL: zookeeper:2181
      START_BLOCK: 52500
      BITCOIND_URL: bitcoind
      BITCOIND_PORT: 8332
      BITCOIND_USER: 
      BITCOIND_PASSWORD:
      KAFKA_TOPIC: btc-transfers
