FROM hseeberger/scala-sbt:8u171_2.12.6_1.1.6

WORKDIR /app

COPY project /app/project/

COPY *.sbt .env /app/

RUN env $(grep -v '^#' .env | xargs) sbt update

#COPY . /app/

#RUN env $(grep -v '^#' .env | xargs) sbt update


CMD env $(grep -v '^#' .env | xargs) sbt '~test' &\
    env $(grep -v '^#' .env | xargs) sbt '~it:test' && fg
