FROM hseeberger/scala-sbt:8u171_2.12.6_1.1.6

ARG UID

RUN useradd --uid $UID dev-user --create-home &&\
    mv /root/.sbt /home/dev-user/.sbt &&\
    chown --recursive dev-user /home/dev-user/.sbt &&\
    chmod --recursive a+rwx /root &&\
    rm -rf /app &&\
    mkdir /app &&\
    chown dev-user /app

WORKDIR /app

USER dev-user

COPY --chown=dev-user project /app/project/

COPY --chown=dev-user *.sbt .env /app/

RUN sbt update

#COPY . /app/

#RUN env $(grep -v '^#' .env | xargs) sbt update

CMD sbt
