version: '3.4'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "127.0.0.1:2181:2181"
    #logging:
    #    driver: none
  kafka:
    image: wurstmeister/kafka
    ports:
      - "127.0.0.1:9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_TRANSACTION_MAX_TIMEOUT_MS: 7200000
    depends_on:
      - zookeeper
    #volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock
    #logging:
    #    driver: none

  consumer:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
      - kafka
    command:
      - kafka-console-consumer.sh
      - --bootstrap-server
      - kafka:9092
      - --topic
      - "${TOPIC}"
      - --property
      - "print.key=true"
      - --property
      - "isolation.level=read_committed"

  sbt:
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        - UID
        - GID

    volumes:
      - .:/app

    depends_on:
      - zookeeper
      - kafka

    command: ["sbt"]
      
    environment:
      KAFKA_URL: kafka:9092
      KAFKA_RAW_BLOCK_URL: kafka:9092
      KAFKA_TRANSFERS_URL: kafka:9092
      ZOOKEEPER_URL: zookeeper:2181
      START_BLOCK: 52500
      BITCOIND_URL: 
      BITCOIND_PORT: 8332
      BITCOIND_USER: 
      BITCOIND_PASSWORD:
      CHECKPOINT_DATA_URI: file:///app/output/checkpoints

  rawexporter:
    build:
      context: .
      target: rawexporter

    depends_on:
      - zookeeper
      - kafka

    environment:
      KAFKA_URL: kafka:9092
      ZOOKEEPER_URL: zookeeper:2181
      BITCOIND_URL:
      BITCOIND_PORT: 8332
      BITCOIND_USER:
      BITCOIND_PASSWORD:

    
  blockprocessor-job-cluster:
    build:
      context: .
      target: blockprocessor
    ports: 
      - "127.0.0.1:8081:8081"
    command: job-cluster --job-classname net.santiment.btc.blockprocessor.Main ${SAVEPOINT_OPTIONS} ${FLINK_JOB_ARGUMENTS}

    depends_on:
      - zookeeper
      - kafka
      - blockprocessor-taskmanager

    volumes:
      - ./conf:/opt/flink/conf
      - ./tmp/jobmanager:/tmp
      - ./output:/output

    environment:
      KAFKA_URL: kafka:9092
      ZOOKEEPER_URL: zookeeper:2181
      CHECKPOINT_DATA_URI: file:///output/checkpoints
      CHECKPOINT_INTERVAL_MS: 5000
      MIN_PAUSE_BETWEEN_CHECKPOINTS: 1000

  blockprocessor-taskmanager:
    build:
      context: .
      target: blockprocessor

    depends_on:
      - kafka

    volumes:
      - ./conf:/opt/flink/conf
      - ./tmp/taskmanager:/tmp
      - ./output:/output
      

    command: "task-manager"
    

volumes:
  kafka_data:
